### ISSUE TITLE
Why readystatechange is not triggered as other events ?

### ISSUE THREAD

**Issue by mjeanroy** [jasmine/jasmine-ajax#102]
Hi,

According to the specification (see [here](http://www.w3.org/TR/XMLHttpRequest/#events) and [here](http://www.w3.org/TR/XMLHttpRequest/#the-send()-method)), event 'readystatechange' should be triggered (as other events).

With jasmine-ajax, each event is correctly triggered except this one. You probably have good reasons for doing this, so why is it different for 'readystatechange' event ?

I forked your repo and I made this fix, I would be happy to submit a PR if you want.

**Comment by slackersoft** [comment]
Looks like we just missed this when working on the other events. It should definitely be able to use the event bus and be triggered like the rest of the events.

We'd be happy to review a pull request for this.
