### ISSUE TITLE
Update bower dependency

### ISSUE THREAD

**Issue by jhaglund** [jasmine/jasmine-ajax#106]
The dependencies in bower.json is ~2.0

Could it be changed to ~2, so we can use jasmine 2.2?

Thanks!

**Comment by ronen** [comment]
Was just about to report this issue myself, and found that you fixed it already.  Would you be willing to tag a release 3.1.1, so I won't need to pull jasmine-ajax from master?

Thanks!

**Comment by slackersoft** [comment]
Released
