### ISSUE TITLE
Events fired do not have expected context and argument

### ISSUE THREAD

**Issue by lokeb** [jasmine/jasmine-ajax#108]
When using the real XHR object, the callbacks get two new objects : 
1. this points to the current XHR object
2. an XMLHttpRequestProgressEvent callback argument

My code listens only to the events load, and progress, which are called as they should, but none of the objects as described above are available in the callback, not even "this", which makes it absolutely useless.

I tried using onload, which does have this pointing to the current fake XHR object, but it still does not have the other callback argument, which is another flaw.

**Comment by slackersoft** [comment]
I'd be happy to review a pull request that passed in the proper ProgressEvent argument and set the `this` context to the XHR when triggering events added with `addEventListener`.

Thanks for using jasmine!
