### ISSUE TITLE
Xhr object should have an upload object as attribute

### ISSUE THREAD

**Issue by mjeanroy** [jasmine/jasmine-ajax#109]
According to the specification (see [here](http://www.w3.org/TR/XMLHttpRequest/#xmlhttprequest) or [here](http://www.w3.org/TR/XMLHttpRequest/#request)), each xhr object should have a unique upload attribute and events (such as 'progress', 'loadstart' etc.) should be fired on this object.

I can submit a PR if you want.

**Comment by slackersoft** [comment]
I'd be happy to review a pull request that enabled this functionality.

**Comment by sgravrock** [comment]
Closing due to sustained lack of user interest.
