### ISSUE TITLE
Add error and timeout to the stubRequest 

### ISSUE THREAD

**Issue by Mordred** [jasmine/jasmine-ajax#111]
Hi, I'm creating and sending XHR inside a then() of the Promise.

```js
Promise.resolve('url').then(function(url) {
  // Send XHR
})

jasmine.Ajax.requests.mostRecent().responseError(); // mostRecent() will return undefined
```

`mostRecent()` will be undefined, because it will be evaluated before XHR is actually sent. So I need to use `stubRequest`. `andReturn` is good enough for testing successful XHRs, but I cannot test errors or timeouts.

It would be great to have something like this:

```js
// For error
jasmine.Ajax
  .stubRequest('http://example.com/some/cool/path')
  .andError();

// For timeout
jasmine.Ajax
  .stubRequest('http://example.com/some/cool/path')
  .andTimeout();
```

**Comment by slackersoft** [comment]
This seems reasonable to me. I'd be happy to review a pull request that added this ability.
