### ISSUE TITLE
How to define AjaxRequestStub with POST response content?

### ISSUE THREAD

**Issue by SunboX** [jasmine/jasmine-ajax#115]
I want to define a `AjaxRequestStub` containing a POST Response. So if a Ajax call is matching the given URL, the POST Content and Headers will be returned automatically.

Using 

```js
jasmine.Ajax.requests.mostRecent().respondWith({
    status: xxx,
    statusText: xxx,
    contentType: xxx,
    responseHeaders: xxx,
    responseText: xxx
});
```
will not work in this case, because some Ajax calls are hidden inside a framework used.

**Comment by SunboX** [comment]
Ah, ok I got it! Maybe this should be mentioned in the docs. :smile: 

```js
jasmine.Ajax.install();
jasmine.Ajax.stubRequest(
    /.*\/path\/to\/be\/called.*/
).andReturn({
    status: xxx,
    statusText: xxx,
    contentType: xxx,
    responseHeaders: xxx,
    responseText: xxx
});
```

**Comment by SunboX** [comment]
Next problem ... I have two different responses with the same URL called. The different responses are depend on the POST content (JSON XML).

How do I differ in the `stubRequest` besed on the POST Content?

**Comment by SunboX** [comment]
Ok, I can fix this by changing `getJasmineRequireObj().AjaxRequestStub` so I can call it like this:

```js
jasmine.Ajax.install();
jasmine.Ajax.stubRequest(
    /.*\/path\/to\/be\/called.*/,
    /.*\<registrationRequest\>.*/
).andReturn({
    status: xxx,
    statusText: xxx,
    contentType: xxx,
    responseHeaders: xxx,
    responseText: xxx
});
```

Changed `getJasmineRequireObj().AjaxRequestStub`:

```js
getJasmineRequireObj().AjaxRequestStub = function() {
  function RequestStub(url, stubData, method) {
    var normalizeQuery = function(query) {
      return query ? query.split('&').sort().join('&') : undefined;
    };

    if (url instanceof RegExp) {
      this.url = url;
      this.query = undefined;
    } else {
      var split = url.split('?');
      this.url = split[0];
      this.query = split.length > 1 ? normalizeQuery(split[1]) : undefined;
    }

    this.data = (stubData instanceof RegExp) ? stubData : normalizeQuery(stubData);
    this.method = method;

    this.andReturn = function(options) {
      this.status = options.status || 200;

      this.contentType = options.contentType;
      this.response = options.response;
      this.responseText = options.responseText;
      this.responseHeaders = options.responseHeaders;
    };

    this.matches = function(fullUrl, data, method) {
      var urlMatches = false;
      fullUrl = fullUrl.toString();
      if (this.url instanceof RegExp) {
        urlMatches = this.url.test(fullUrl);
      } else {
        var urlSplit = fullUrl.split('?'),
            url = urlSplit[0],
            query = urlSplit[1];
        urlMatches = this.url === url && this.query === normalizeQuery(query);
      }
      var dataMatches = false;
      if (this.data instanceof RegExp) {
        dataMatches = this.data.test(data);
      } else {
        dataMatches = !this.data || this.data === normalizeQuery(data);
      }
      return urlMatches && dataMatches && (!this.method || this.method === method);
    };
  }

  return RequestStub;
};
```

**Comment by SunboX** [comment]
should I open a pull request for this?

**Comment by slackersoft** [comment]
I think it probably makes sense to allow the `data` to be matched with a `RegExp` as well as the query params. I'd be happy to review a pull request for that.

**Comment by purtuga** [comment]
For anyone else who might have landed here after doing a search on the issues for `query.split`.  This fix is not yet part of a version (ex. not in v3.1.1), although the documentation already reflects use of it on the main page of this repo. If you are trying to use this and get this error:

`TypeError: query.split is not a function`

then just install the `master` branch and it should work after that. Here is what I used in `bower.json` (or you can use it `package.json` as well):

`"jasmine-ajax": "git@github.com:jasmine/jasmine-ajax.git#master"`

/paul

**Comment by slackersoft** [comment]
The fix should be available in 3.2.0

**Comment by SunboX** [comment]
:+1:

**Comment by purtuga** [comment]
+1 thanks
