### ISSUE TITLE
Proxy Functionality not available

### ISSUE THREAD

**Issue by rbansod** [jasmine/jasmine-ajax#117]
Is there a way to directly retrieve the json from file by giving url such as giving a proxy for response in the current version

**Comment by slackersoft** [comment]
I'm not totally sure what you're asking for here.

Do you want the ability to record a response for later? I'm not sure where we would be able to save the response, given that jasmine-ajax runs in the browser which generally doesn't have access to the local file system.

If not that, can you give me an example of what you would want to happen?

**Comment by rbansod** [comment]
What I am trying to say here is it is missing the ability to pull response from a file in local system.

**Comment by slackersoft** [comment]
Browsers generally don't allow javascript on the page to access the local filesystem, so I don't think what you are suggesting is actually possible.

**Comment by rbansod** [comment]
Imagine a simple json file available on your system which has data. Now instead of using adding data manually from the file to response text field we could directly use it from the directory path that we give. Kinda what mockjax has for the request redirection. Please check http://github.com/jakerella/jquery-mockjax/

**Comment by slackersoft** [comment]
One of the goals of using jasmine-ajax is to allow you to remove all real XHRs from your code so your tests can execute synchronously without waiting for a server to respond. If you want to set up a response before you begin executing your tests you should be able to use the `stubRequest` syntax. See the [docs here](http://jasmine.github.io/edge/ajax.html)

This isn't functionality that we want in jasmine-ajax, so I'm going to close this.

Thanks for using jasmine.
