### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'evt.lengthComputable') when using with dojo 1.9.1

### ISSUE THREAD

**Issue by stevezxu** [jasmine/jasmine-ajax#119]
Get the following error when using with dojo 1.9.1. Here is the stack:

TypeError: 'undefined' is not an object (evaluating 'evt.lengthComputable')
	    at onProgress (dojo-release-1.9.1/dojo/dojo.js.uncompressed.js:11670)
	    at /karma-jasmine-ajax/node_modules/jasmine-ajax/lib/mock-ajax.js:88
	    at /karma-jasmine-ajax/node_modules/jasmine-ajax/lib/mock-ajax.js:355

passing event to listener on line 88 fixes the issue:        eventListeners[i](event);

**Comment by stevezxu** [comment]
Actually, nvm. I was using karma-jasmine-ajax, which is using earlier version of jasmine-ajax. It seems the problem has already addressed within 3.1.1. I will contact author of karma-jasmine-ajax to use the latest version of jasmine-ajax. 

Thanks,

**Comment by mjeanroy** [comment]
Hi,
Your issue will not be fixed with 3.1.1, but it has been fixed with PR #114 which has not been released yet.

**Comment by stevezxu** [comment]
thanks.

**Comment by mjeanroy** [comment]
Hi,
It should be fixed with the recent version 3.2.0, do you confirm ?

**Comment by lobsteropteryx** [comment]
Don't mean to butt in, but I can confirm that the 3.2 release fixed this issue for me.

**Comment by mjeanroy** [comment]
Glad to hear it !
Need a confirmation from @stevezxu and this issue could probably be closed, do you agree @slackersoft ?

**Comment by slackersoft** [comment]
We have one confirmation already, so if @stevezxu doesn't confirm in a few days, I'll probable just close this.

**Comment by slackersoft** [comment]
Sounds like this has been fixed. Closing
