### ISSUE TITLE
Jasmine ajax stub async?

### ISSUE THREAD

**Issue by scottwio** [jasmine/jasmine-ajax#120]
I have a jasmine ajax stub in my before each block that looks like this

    jasmine.Ajax.stubRequest('testpage.html').andReturn(
      {
        responseText: JSON.stringify(window.__html__['src/sign-up/testpage.html'])
      }
    );

My understanding is that whenever a request is now made to testpage.html it will return the response object in a synchronous manner. However this doesn't seem to be the way it's functioning the response is returned async. Is async the correct behavior and if so how would I make this return data synchronously?

**Comment by mmautner** [comment]
I think you're looking for jasmine/jasmine#526

**Comment by scottwio** [comment]
Thanks mmautner, isn't done meant for async I'm looking for a synchronously way of returning data from a request to a specific URL

**Comment by slackersoft** [comment]
A stubbed request should cause the XHR to be completed inline when the request is made. See https://github.com/jasmine/jasmine-ajax/blob/master/src/fakeRequest.js#L169 for the actual code when a stub is found for a given request. If this is not what you're seeing, can you supply an example spec that demonstrates the issue so we can get it fixed?

Thanks

**Comment by slackersoft** [comment]
Closing this as we haven't heard anything else from the community on this issue. If you're still seeing an issue, please provide a sample spec so we can debug.

Thanks for using jasmine!
