### ISSUE TITLE
REST.js calls hang

### ISSUE THREAD

**Issue by sebastianovide** [jasmine/jasmine-ajax#122]
Hi

I'm replacing jquery.ajax with REST.js, and for some reason my test hang

    beforeEach(function() {
      jasmine.Ajax.install();
    });

      it('sets ajax default url', function(done) {
        var myClient = new MyClient(serverUrl);

        myClient
          .client('/')
          .then(function(response) {
            console.log("THEN -->  " + JSON.stringify(response));
            var request = jasmine.Ajax.requests.mostRecent();
            expect(request.url).toContain(serverUrl);
            done();
          })
          .catch(function(response) {
            console.log("CATCH -->  " + JSON.stringify(response));
            expect(JSON.stringify(response)).toBe(undefined);
            done();
          });

          console.log("IT --> ");
      });

It display "IT -->" and after few seconds it just times out. If I comment out "jasmine.Ajax.install();", then it would print "CATCH --> xxxx"

Any ideas ?

Thanks

**Comment by slackersoft** [comment]
I don't see anywhere in your test where you tell jasmine-ajax to complete the request. You need to use either `stubRequest` before you make the request or call `jasmine.Ajax.requests.mostRecent().respondWith()` the request is made to make it complete at that time.

**Comment by slackersoft** [comment]
We haven't heard anything else on this from the community, so I'm going to close this.
