### ISSUE TITLE
readyState === 0 on responseTimeout and responseError

### ISSUE THREAD

**Issue by jdbevan** [jasmine/jasmine-ajax#125]
I wouldn't expect the readyState to be 0 on a request timeout or on an error as they should have at least made the request to the server: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

In fact, in my production code I have to check for readyState > 0 to ensure the request has actually been made/started to avoid reporting spurious errors.

Here's some tests to demonstrate:

```
describe("ajax error failure",() => {
    beforeEach(() => {
        jasmine.Ajax.install();
        jasmine.clock().install();
    });

    afterEach(() => {
        jasmine.Ajax.uninstall();
        jasmine.clock().uninstall();
    });

    it("should be true: non aborted error", (done) => {

        var readyState = -1;

        $.ajax({
            url: "http://example.com"
        }).done(() => {
            // do nothing
        }).fail((jqXHR, textStatus, error) => {
            readyState = jqXHR.readyState;
        }).complete(() => {
            expect(readyState).not.toBe(0);
            done();
        });

        jasmine.Ajax.requests.mostRecent().responseError();
    });

    it("shuold be true: non aborted timeout", (done) => {

        var readyState = -1;

        $.ajax({
            url: "http://example.com",
            timeout: 5000
        }).done(() => {
            // do nothing
        }).fail((jqXHR, textStatus, error) => {
            readyState = jqXHR.readyState;
        }).complete(() => {
            expect(readyState).not.toBe(0);
            done();
        });

        jasmine.Ajax.requests.mostRecent().responseTimeout();
    });

});
```

**Comment by slackersoft** [comment]
What version of jasmine-ajax are you using? `responseTimeout` should be setting the `readyState` to 4. See: https://github.com/jasmine/jasmine-ajax/blob/master/src/fakeRequest.js#L275

**Comment by jdbevan** [comment]
I'm using karma-jasmine-ajax which specifies ^3.0.0 as the version of jasmine-ajax to use and when I run npm install using the package.json file in the gist below it installs v3.1.1

Here's a gist with the relevant files to reproduce the problem: https://gist.github.com/jdbevan/735d552e1e85e95a2584

I'm running node v0.12.2

**Comment by jdbevan** [comment]
I noticed in the source that readyState was being set to 4 which is what led me to file a bug report.

**Comment by slackersoft** [comment]
It looks like jQuery actually ignores the `readyState` set on the actual XHR in the case of an error or timeout. jQuery appears to look only at the `status` (HTTP response code) of the XHR when handling state changes, and only sets its internal `jqXHR.readyState` to `4` when the HTTP status is greater than `0`.

We can fix the error case with a hack so that the response code passes that check, but the jQuery timeout code explicitly uses `0` for the status. This really seems like a bug in jQuery, that it is not respecting the `readyState` of the underlying XHR.

**Comment by jdbevan** [comment]
Ah ok, thanks for looking into that. I'll close this issue.
