### ISSUE TITLE
3.2.0 is not published in NPM

### ISSUE THREAD

**Issue by morsdyce** [jasmine/jasmine-ajax#126]
Latest version in NPM is 3.1.1

Can you please publish it?
Thanks

**Comment by gf3** [comment]
:+1:

**Comment by slackersoft** [comment]
Sorry about that, something must have broken with the release script. I should be able to get it released tomorrow.

**Comment by slackersoft** [comment]
[done](https://www.npmjs.com/package/jasmine-ajax)
