### ISSUE TITLE
SyntaxError: Unable to parse JSON string

### ISSUE THREAD

**Issue by russback** [jasmine/jasmine-ajax#129]
When sending this response:

````
    jasmine.Ajax.requests.mostRecent().respondWith({
            "status": 200,
            "contentType": 'json',
            "responseText": 'hello'
   });
````

To an jQuery Ajax call that expects a `dataType` of `json`, I'm getting an error with the following message:

`SyntaxError: Unable to parse JSON string`

Setting `dataType` to `text` works but that means I'm changing my source function, which I don't want to do.

**Comment by mjeanroy** [comment]
String "hello" is not a valid json object, so parsing it with native JSON.parse throw this error, this is not a bug with jasmine-ajax.

**Comment by russback** [comment]
Yes my apologies, I was considering the object I was passing to `respondWith` rather than the `responseText` property.
