### ISSUE TITLE
ability to disable fixture cleanUp between specs

### ISSUE THREAD

**Issue by jywarren** [jasmine/jasmine-ajax#139]
I've added a way to disable fixture teardown by disabling the cleanUp method; a bit messy, but for when fixture generation is expensive, or the environment is complex enough that I want to test a series of things in a persistent environment. 

I know not everyone wants this -- there's a lot to be said for small, self-contained specs and contexts, but is there any interest in building such a feature into jasmine-ajax?

````js
  var cleanUp;

  // disable cleanUp() method to persist the fixture across specs
  persistFixture = function() {

    cleanUp = jasmine.getFixtures().cleanUp; // save the cleanUp function

    jasmine.getFixtures().cleanUp = function() {}; // replace it with a fake one

  }

  // restore non-persistent fixture behavior
  unPersistFixture = function() {

    jasmine.getFixtures().cleanUp = cleanUp;

  }
````

**Comment by jywarren** [comment]
Er, obviously it'd be easier to do in the library itself with a switch instead of the jiggery-pokery above, i just thought I'd share how I did it for clarity.

**Comment by slackersoft** [comment]
I'm not sure where you're getting the `getFixtures` function from, but it isn't from jasmine itself or jasmine-ajax. I'm not even sure which library is adding that function.

I'm going to close this since it isn't actually related to this repo. Thanks for using jasmine!

**Comment by jywarren** [comment]
Omg sorry, I'm just too bleary eyed here. Meant to post to [jasmine-jquery](https://github.com/velesin/jasmine-jquery), not jasmine-ajax. My bad!
