### ISSUE TITLE
Can not set a status code of 0 on a stubRequest

### ISSUE THREAD

**Issue by bhellema** [jasmine/jasmine-ajax#141]
When stubbing out a request, you can not set the status value to 0 [0].  Even thought the HTTP status codes do not contain a valid code for 0, the value being manipulated results in the XMLHttpRequest's status code value which can contain a value of 0 [1]. (if I have this correct)

```
jasmine.Ajax.stubRequest(
     /.*\/j_security_check/
).andReturn({
     status: 0
});
```

[0] - https://github.com/jasmine/jasmine-ajax/blob/8b68db5163fd21ee70b1256e978a68cbe7f5d7d0/src/requestStub.js#L25
[1] - http://www.w3.org/TR/XMLHttpRequest/#the-status-attribute

This was discovered as part of my unit testing trying to handle a case when the XHR (connection to the server is down) which cause the XMLHttpRequest to have a status code of 0.

There is a work around setting the value to a string of "0" which does have a side effect of changing the code using the XHR to check for == 0 and not === 0.

**Comment by slackersoft** [comment]
The goal of that code is simply to provide a default value if the stub doesn't specify one. I would be happy to review a pull request that kept the defaulting functionality, but allowed `0` to not cause the fallback.

This could either be checking for `null` or `undefined` or checking if the result provided includes the key at all.
