### ISSUE TITLE
Author request headers should be reset in the open method

### ISSUE THREAD

**Issue by mooglemoogle** [jasmine/jasmine-ajax#142]
We have a strange situation where we are reusing xmlhttprequests in some cases after they have returned an error. In attempting to test this, I realized that the fake xhr that is made in this library and the real one act slightly differently in these cases. In the browser, the request headers are cleared out before the second send happens where the fake xhr does no such clearing.

I looked into the standard and it mentions that the author request headers should be set to the empty list during the open method.

http://www.w3.org/TR/XMLHttpRequest/#the-open()-method See step 14.

**Comment by slackersoft** [comment]
I would be happy to review a pull request that fixes this.
