### ISSUE TITLE
How to set response headers for mocked ajax requests?

### ISSUE THREAD

**Issue by amit1911** [jasmine/jasmine-ajax#144]
I am mocking an ajax request using jasmine-ajax as follows
```
jasmine.Ajax.requests.mostRecent().respondWith({
    "status": 200,
    "responseText": '{}'
});
```
I am trying to get the 'Location' header for the request object passed to the ajax success callback as follows:
```
success(function(data, textStatus, request) {
    var url = request.getResponseHeader('Location');
    url = url.substring(...);
}
```
but it returns null and the jasmine test fails because substring function is called on null. What should I do? Note: I can access the 'Location' header just fine if the ajax request is not mocked.

**Comment by slackersoft** [comment]
In your call to `respondWith` you should be able to provide a `responseHeaders` key.

I've also created an issue on the docs site jasmine/jasmine.github.io#54 to add this to the existing docs.

Thanks for using Jasmine!
