### ISSUE TITLE
What browsers are supported?

### ISSUE THREAD

**Issue by mzabriskie** [jasmine/jasmine-ajax#149]
I am using jasmine-ajax for testing [axios](https://github.com/mzabriskie/axios) and it has worked very well. I am now moving my tests to run on Sauce Labs and am running into problems when testing on IE10 and below.

My test looks something like this:

```js
describe('request', function () {
  beforeEach(function () {
    jasmine.Ajax.install();
  });

  afterEach(function () {
    jasmine.Ajax.uninstall();
  });

  it('should make a request', function (done) {
    axios('/foo');

    setTimeout(function () {
      var request = jasmine.Ajax.requests.mostRecent();
      expect(request.url).toBe('/foo');
      done();
    }, 0);
  });
});
```

This works in every other browser I have tested (Firefox, Chrome, Safari, Edge, IE11), but in IE10 and below I get: `TypeError: Unable to get property 'url' of undefined or null reference`. For some reason `jasmine.Ajax.requests.mostRecent()` is returning `undefined`.

Any idea what may be happening? Is IE10 supported, or am I just doing something wrong?

Thanks for your time and for a great lib!

**Comment by slackersoft** [comment]
We currently run our specs on IE 8-11 using SauceLabs on Travis, and everything has been working. Looking at the axios docs, it doesn't look like they are actually running their tests agains IE versions 8-10.

This seems like it's probably an issue with axios and not jasmine-ajax, in that no actual ajax request is being made.

**Comment by mzabriskie** [comment]
Thanks for your response. I am the author of axios. You are correct that it's not running against IE 8-10. I just hooked axios up with SauceLabs yesterday, but am getting the error described above so I had to take those browsers out for the time being.

It sounds like you support IE 8-11, so maybe it is something on my end. Thanks again.

**Comment by mzabriskie** [comment]
Just wanted to document that I got this working. I simply had to increase the delay in my `setTimeout` from 0 to 1.

**Comment by UnsungHero97** [comment]
@mzabriskie can you explain why you need to actually use `setTimeout`? is there some compatibility issue with Promises?
