### ISSUE TITLE
jasmine-ajax break sourcemap support

### ISSUE THREAD

**Issue by llCorvinSll** [jasmine/jasmine-ajax#153]
when use jasmine-ajax with karma in Chrome browser. 
on failed test always throws 
`Uncaught TypeError: Cannot read property 'length' of undefined`

stack trace:
![Error](http://imageshack.com/a/img921/2724/Gqnn2b.png)

seems jasmine-ajax crack when browser try to download sourcemap
this behavior repeated even with inline sourcemaps

**Comment by barsukov** [comment]
Yes I have the same issue in this case only when I have error. Please somebody have a look on it. This really anoying issue.

**Comment by apepper** [comment]
Fixed since `3.3.0` (see https://github.com/jasmine/jasmine-ajax/blob/master/release_notes/3.3.0.md for details).
