### ISSUE TITLE
stubRequest does not seem to play nicely with Rails `remote: true` (jquery-ujs)

### ISSUE THREAD

**Issue by vaharoni** [jasmine/jasmine-ajax#154]
I have a link in Rails:

``` ruby
<%= link_to 'click here', '/some_path', class: 'special-link', remote: true %>
```

and some JS code intended to have an effect on the DOM:

``` coffeescript
$(document).on 'ajax:success', '.special-link', (e, data, status, xhr) ->
  # Code that has some effect on the DOM as a function of the server response
```

When I try to test the library in Jasmine by calling `$('.special-link').click()`, the AJAX request occurs but the desirable effect on the DOM cannot be observed. The issue, it seems, is that the `ajax:success` event does not get triggered:

``` coffeescript
describe 'my library', ->
  beforeEach ->
    MagicLamp.load('fixture') # Fixture library that injects the link above to the DOM
    jasmine.Ajax.install()
    jasmine.Ajax.stubRequest('/some_path').andReturn({
      responseText: 'response that is supposed to trigger some effect on the DOM'})

  afterEach ->
    jasmine.Ajax.uninstall()

  # Works. The fixtures are loading properly
  it '[sanity] loads fixtures correctly', ->
    expect($('.special-link').length).toEqual(1)

  # Works. The jquery-ujs correctly triggers an ajax request on click
  it '[sanity] triggers the ajax call', ->
    $('.special-link').click() 
    expect(jasmine.Ajax.requests.mostRecent().url).toContain('/some_path')

  # Does not work. 
  it 'knows how to handle ajax:success events', ->
    spy = jasmine.createSpy('my spy')
    $('.special-link').on 'ajax:success', spy
    $('.special-link').click()
    expect(spy).toHaveBeenCalled()
```

Am I missing something? What's the recommended way to black-box test effects on DOM of jquery-ujs events?

Thanks.
Amit

**Comment by slackersoft** [comment]
Jasmine-Ajax just replaces the `XmlHTTPRequest` constructor on `window` with a fake implementation, so any jQuery magic that happens on top of that should stay intact.

Given that most of the code you're working with here is written by other people (jQuery-UJS), I'm not totally sure that something like a unit level test with an AJAX mock is the right level of granularity to test at. Perhaps a selenium/phantom test with the full page.

**Comment by slackersoft** [comment]
We haven't heard anything from the community on this issue in a while. Closing.
