### ISSUE TITLE
TypeError: fs.readdirSync is not a function

### ISSUE THREAD

**Issue by CookPete** [jasmine/jasmine-ajax#155]
Since 5dc127d492502b734e0dcaa8978f16dbebcf77fe I have been getting errors when testing:

```
TypeError: fs.readdirSync is not a function. (In 'fs.readdirSync(rootPath)', 'fs.readdirSync' is undefined)
```

I am using [karma-webpack](https://github.com/webpack/karma-webpack) and it looks like [this line](https://github.com/jasmine/jasmine-ajax/blob/5dc127d492502b734e0dcaa8978f16dbebcf77fe/src/boot.js#L37) is causing the issue, as `jasmine-core` [tries to use fs](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/lib/jasmine-core.js#L14) in the browser, which fails.

**Comment by jekill** [comment]
@CookPete Hello.
I always get this error too.
Have you solved this problem?

**Comment by slackersoft** [comment]
Jasmine-Ajax is probably loading the wrong thing when it is in a RequireJS environment to ensure that jasmine-core has already been initialized. The `jasmine-core.js` is there to boot up jasmine in a node environment (hence the `fs` calls) and thus shouldn't be used in a browser.

We would be happy to review a pull request (or set of them if something else is needed in core) to allow Jasmine-Ajax to require Jasmine-Core in RequireJS without NodeJS.
