### ISSUE TITLE
Uncaught ReferenceError: getJasmineRequireObj is not defined

### ISSUE THREAD

**Issue by mhdSid** [jasmine/jasmine-ajax#156]
Karma Version: "0.12.37"
karma-jasmine-ajax Version: "0.1.13"

Karma config file is configured properly, however, I'm getting this error when I call jasmine.Ajax.install()

Stackoverflow question url: http://stackoverflow.com/questions/37810343/why-am-i-getting-this-error-when-calling-the-method-jasmine-ajax-install

**Comment by slackersoft** [comment]
Sounds like there isn't a Jasmine available on the page. Jasmine-Ajax relies on Jasmine having already been set up when it is loaded. This also means that Jasmine needs to be loaded before Jasmine-Ajax is included.

Hope this helps. Thanks for using Jasmine!

**Comment by tomalec** [comment]
@slackersoft, It seems this error occurs even if Jasmine is available.
I'm loading jasmine-ajax once Jasmine is available (as suggested in READMe with `require('jasmine-ajax')` in helper, 
**SpecHelper.js**:
```js
console.info("Running jasmine.version = " + jasmine.version);
// load jasmine.Ajax if needed (for node runners)
if(typeof jasmine.Ajax === 'undefined'){
   require('jasmine-ajax');
}
```

And i get 
```

Running jasmine.version = 2.5.2
D:\repos\PolymerPlayground\puppet\PuppetJs\node_modules\jasmine-ajax\lib\mock-ajax.js:33
getJasmineRequireObj().ajax = function(jRequire) {
^

ReferenceError: getJasmineRequireObj is not defined
    at Object.<anonymous> (D:\repos\PolymerPlayground\puppet\PuppetJs\node_modules\jasmine-ajax\lib\mock-ajax.js:33:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\repos\PolymerPlayground\puppet\PuppetJs\test\SpecHelper.js:11:5)
    at Module._compile (module.js:570:32)
```

**Comment by slackersoft** [comment]
It's starting to look like we'll need to revisit how Jasmine-Core is packaged up for the various environments to make this all work. Currently the thing available via `require('jasmine-core');` is assuming it is being loaded in a node.js context and thus has access to things like `fs`. There is also some work being attempted in Jasmine-Core around this: see jasmine/jasmine#970 and #150 here.

We've taken a couple of Pull Requests to try to make Jasmine-Ajax work in a node.js fake browser type environment, but it's not a fully supported setup at this time.
