### ISSUE TITLE
Release a new version to pick up .andCallFunction

### ISSUE THREAD

**Issue by AnilRedshift** [jasmine/jasmine-ajax#165]
Hello,

I have a need for the .andCallFunction() implementation added by https://github.com/jasmine/jasmine-ajax/commit/33b9baa2dffdb0768cd59dd5dfb4ff3ca55f85f7

However, the last time `jasmine-ajax` was published to npm was a year ago. Can you please rev a new version?

Thanks!

**Comment by slackersoft** [comment]
[3.3.0](https://github.com/jasmine/jasmine-ajax/releases/tag/v3.3.0) has been released
