### ISSUE TITLE
Only the first XHR is captured when running multiple test suites

### ISSUE THREAD

**Issue by XDex** [jasmine/jasmine-ajax#167]
I'm using Karma with karma-jasmine-ajax and jasmine-ajax@3.2.0.
The issue occurs when I run a suite of multiple test suites with Karma, specifically only the XHR from the first suite is successfully intercepted and available in `jasmine.Ajax.requests.mostRecent()`
The second spec's `jasmine.Ajax.requests.count()` run after the XHR returns 0.
I'm doing `jasmine.Ajax.install()` in beforeEach() and `jasmine.Ajax.uninstall()` in afterEach() block of each test suite. I'm also using karma-fixture and also load the fixtures before installing jasmine-ajax, as recommended.
Notice: when running the test suites separately, each test suite runs successfully, i.e. XHRs are intercepted in both cases, the issue occurs only when Karma runs all of the suites one after another.

**Comment by XDex** [comment]
Here's a code sample reproducing the issue:
```javascript
describe("Suite #1", function() {
  beforeEach(function () {
    fixture.setBase('fixtures');

    json_fixture = fixture.load('tc2.json', true);

    TestResponses = {
      resp1: {
        error: {
          status: 200,
          responseText: JSON.stringify(json_fixture)
        }
      }
    };

    jasmine.Ajax.install();
  });

  it("should fire error when response is error", function(done) {
    ajaxCallFunc({
      success: function(data) {
        done.fail('success should not be called');
      },
      error: function(status, error) {
        expect(status).toBe("error");
        expect(error).toBe("tc2");
        done();
      }
    });

    console.log('Count: ', jasmine.Ajax.requests.count());
    
    request = jasmine.Ajax.requests.mostRecent();

    request.respondWith(TestResponses.resp1.error);
  }, 1000);

  afterEach(function () {
    jasmine.Ajax.uninstall();
    fixture.cleanup();
  });
});

describe("Suite #2", function() {
  beforeEach(function (done) {
    fixture.setBase('fixtures');
    html_fixture = fixture.load('tc5.html', true);
    json_fixture = fixture.load('tc5.json', true);

    TestResponses = {
      resp1: {
        success: {
          status: 200,
          responseText: JSON.stringify(json_fixture)
        }
      }
    };
  
    jasmine.Ajax.install();

    ajaxCallFunc({
      success: function(data) {
        setDataInFixtureHtml(data);

        setTimeout(function() {
          done();
        }, 500);
      },
      error: function(error) {
        done.fail('Error should not be fired: ' + error);
      }
    });

    console.log('Count: ', jasmine.Ajax.requests.count());

    request = jasmine.Ajax.requests.mostRecent();

    request.respondWith(TestResponses.resp1.success);

  }, 1000);

  it("should modify content", function() {
    expect(html_fixture[0].textContent).toEqual('test1');
    expect(html_fixture[1].textContent).toEqual('test2');
    expect(html_fixture[2].textContent).toEqual('test3');
  });

  afterEach(function () {
    jasmine.Ajax.uninstall();
    fixture.cleanup();
  });
});
```
Note: ajaxCallFunc() and setDataInFixtureHtml() are not provided..

**Comment by slackersoft** [comment]
I'm not able to reproduce this issue. I took your spec and commented out the `fixture.setBase` lines and just hard-coded the fixture variables, and I'm seeing:

```
Count:  1
Count:  1
```

In my console. My sample implementation is:

```javascript
function ajaxCallFunc(options) {
  $.ajax('/foo/bar.json', options);
}
```

Additionally, you shouldn't need your specs to also be async unless you're doing something else async in them. Because of how Jasmine-Ajax mocks out the underlying `XMLHttpRequest` object your requests will complete inline.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't been able to reproduce this issue and haven't heard anything back on it, so I'm going to close this. If you are still seeing issues we would be happy to look into them further with a bit more information.

Thanks for using Jasmine!
