### ISSUE TITLE
Correct way to send application/xml response

### ISSUE THREAD

**Issue by muhammad-ammar** [jasmine/jasmine-ajax#170]
I am sending an xml response with application/xml contentType like below

```JS
request.respondWith(
    {
        status: 403,
        contentType: 'application/xml',
        responseText: '<Error><Message>Invalid access key.</Message></Error>'
    }
);
```

But in the fail handler i received `data.jqXHR.responseText` set to `"[object XMLDocument]"` which is incorrect.

```JS
uploadFail: function(event, data) {
    var responseText = data.jqXHR.responseText,
        message = this.defaultMessage;

    if (responseText && data.jqXHR.getResponseHeader('content-type') === 'application/xml') {
        message = $(responseText).find('Message').text();
    }

    this.showFailureMessage(message);
}
```

I am not sure what i am doing wrong. Any help would be appreciated.

**Comment by muhammad-ammar** [comment]
I have also tried the below but it only works if `contentType` is set to `application/xml;charset=UTF-8` but i want to set `application/xml` only.

```JS
jasmine.Ajax.stubRequest(
    /http:\/\/s3.aws.com\/upload\/videos\/.*/
).andReturn({
    status: 403,
    contentType: 'application/xml',
    responseText: '<Error><Message>Invalid access key.</Message></Error>'
});
```

**Comment by muhammad-ammar** [comment]
@slackersoft ^^

**Comment by slackersoft** [comment]
Jasmine-Ajax shouldn't be doing any translation on the `responseText` that is passed to it. What version of Jasmine-ajax are you using?

Jasmine-Ajax will try to parse the `responseText` into an XML document in the `responseXml` property if it detects that the response type is XML. It's possible that the library you're using to wrap the ajax request (jQuery?) is messing with that afterwards.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything else on this issue in a while, so I'm going to close it. Thanks for using Jasmine!
