### ISSUE TITLE
3.3.1 getResponseHeader undefined in FakeXMLHttpRequest

### ISSUE THREAD

**Issue by amaschas** [jasmine/jasmine-ajax#172]
I'm attempting to test an AJAX request via this method:

```
jasmine.Ajax.stubRequest(<url>).andReturn({
  status: 200,
  statusText: 'HTTP/1.1 200 OK',
  contentType: 'application/json;charset=UTF-8',
  responseText: {
    testing: true
  }
});
```

I'm using a library called `xhr-promise`, which runs this check:

https://github.com/scottbrady/xhr-promise/blob/master/lib/xhr-promise.js#L159-L168

If I step through that check in the Chrome debugger, `getResponseHeader` doesn't appear to be defined in any way in the `FakeXMLHttpRequest`. I've tried to pass in a stub `getResponseHeader` in the object I pass to `andReturn`, but it doesn't appear to populate the resulting `FakeXMLHttpRequest`. Is there a way to do this that I'm missing?

**Comment by slackersoft** [comment]
The `FakeXMLHttpRequest` should definitely have a `getResponseHeader` method from its prototype (https://github.com/jasmine/jasmine-ajax/blob/master/src/fakeRequest.js#L213). In fact, the `respondWith` method (which is also used when you use the `stubRequest` as above), actually calls it as well (https://github.com/jasmine/jasmine-ajax/blob/master/src/fakeRequest.js#L280).

I'm not sure what could be happening to cause this issue. Is xhr-promise wrapping up the `XMLHttpRequest` constructor in some way that might interfere with Jasmine-Ajax replacing the one on `window`?

Hope this helps. Thanks for using Jasmine!

**Comment by amaschas** [comment]
Thanks for your response slackersoft. I dug back into my problem in light of the information you provided, and it seems the problem must be on the library side. I'll redirect to them and close this.
