### ISSUE TITLE
Feature Request: support responseJSON

### ISSUE THREAD

**Issue by k-funk** [jasmine/jasmine-ajax#177]
My tests have `.respondWith({ ..., responseText: JSON.stringify({...}), ...})` all over it. Any chance of being able to use `{..., responseJSON: {...}, ... }` in the future?

**Comment by slackersoft** [comment]
We would be happy to review a pull request to allow `responseJSON` to be specified for the response in place of the `responseText` and optionally the `responseType`. I would expect completing a response in this manner would correctly set the `responseText` and default the `responseType` to json.

Thanks for using Jasmine!
