### ISSUE TITLE
Asynchronous stub requests not working with jQuery 2.x

### ISSUE THREAD

**Issue by thayerj** [jasmine/jasmine-ajax#90]
HI,

I created a test to mimic two rapid fire AJAX requests to the same server, however the requests are no longer executed in an asynchronous fashion after updating to jQuery 2.1.3.  You can see the issue [here](http://jsfiddle.net/nnq9qnLa/5/) on JSFiddle.  The console will provide the order of events.

In the previous release of jQuery I was using (1.11.0), 'xhr.onload()' was not declared before the request was stubbed by Jasmine.  As a result, upon reaching the 'this.events.load()' line within the 'respondWith' function, nothing was executed.  It wasn't until the request was returned to jQuery with a 'readyState = 4' that the 'onload' callback was referenced within a setTimeout function without a defined time value.

My Fix:
With the latest jQuery release, xhr.onload is defined before the request is stubbed by Jasmine thus when 'this.events.load()' is called within 'respondWith', the callback is immediately executed.  To fix this, I added an 'if' and setTimeout within the wrapProgressEvent function as shown below:

```javascript
  function wrapProgressEvent(xhr, eventName) {
    return function() {
      if (xhr[eventName]) {
        if (eventName == "onload") {
          setTimeout(xhr[eventName]);
        } else {
          xhr[eventName]();
        }
      }
    };
  }
```

**Comment by slackersoft** [comment]
The intent of using the `andReturn` syntax is basically to make the request synchronous, thus running the callback in the same stack as the ajax call itself. If you want more control over when the ajax call returns you should call `respondWith` yourself.

It looks to me from your fiddle, that the response is being reported correctly. So, when you say it is "not working" what exactly do you mean?

**Comment by thayerj** [comment]
Thanks for the quick response.  I understand from the Jasmine documentation that the requests are to be returned immediately when using the `andReturn` syntax, however if you toggle between jQuery libraries (versions 1.8 - 1.11) on the [JSFiddle](http://jsfiddle.net/nnq9qnLa/5/) from above, you will see that the callback is not run in the same stack as the ajax call itself.

If that is intended behavior for `andReturn`, I will make sure to use `respondWith` for all async calls in the future, but I thought I would mention this since there appears to be a functionality discrepancy with Jasmine between jQuery versions.

**Comment by slackersoft** [comment]
The intent behind the `andReturn` syntax is basically to be able to write a spec like:

````javascript
it('ajax', function() {
  jasmine.Ajax.install();
  jasmine.Ajax.stubRequest('go/url').andReturn({"responseText": "synchronous"});

  var success = jasmine.createSpy('success');

  $.get('go/url').success(success);

  expect(success).toHaveBeenCalled();
});
````

If you do a `setTimeout` the success won't have been called until the next time the spec gives up control, so the `expect` will fail.

Is this causing some test to fail for you or just to have things run in a different order than you expected?

**Comment by thayerj** [comment]
I tried the above code in a few different browsers, but the spec fails.  See end of the script box in the updated [JSFiddle](http://jsfiddle.net/nnq9qnLa/9/).  From what I can see, there appears to be different functionality with the `andReturn` in terms of how the ajax request is initiated.

**Comment by slackersoft** [comment]
Sorry, I should have prefixed that code that, I just wrote it straight in the github comment box. This should work:

````javascript
it('ajax', function() {
  jasmine.Ajax.install();
  jasmine.Ajax.stubRequest('go/url').andReturn({"responseText": "synchronous"});

  var success = jasmine.createSpy('success');

  $.get('go/url', {done: success});

  expect(success).toHaveBeenCalled();
});
````

**Comment by thayerj** [comment]
The `success` spy in the code above is called because it is used as a parameter that is passed to the `go/url` address, not as a result of the success of the `XHR` request.  Additionally, the above `stubRequest` is not called since the URL it is stubbing is different from the URL that is passed with the `XHR` request due to the `done` parameter.

It seems that regardless of the way in which the`XHR` request is invoked, jasmine-ajax's functionality with jQuery 2.X (synchronous AJAX calls) differs from that of jQuery 1.8 - 1.11 (asynchronous AJAX calls).  Moving forward I will use the `respondWith` function to create async calls as needed.

Thank you for your time.
