### ISSUE TITLE
getAllResponseHeaders() should have a trailing CRLF

### ISSUE THREAD

**Issue by dlockhart** [jasmine/jasmine-ajax#91]
I ran into this issue when using jasmine-ajax v2.99.0 with [superagent](https://github.com/visionmedia/superagent) v0.21.0. The issue happens when you use `respondWith` that has `responseHeaders` -- the last header will get stripped by superagent.

So when you do the following:

    jasmine.Ajax.requests.mostRecent().respondWith( {
      status: 200,
      responseHeaders: {
        allow: 'GET'
      }
    });

In jasmine-ajax's [`fakeRequest.js`, line 215](https://github.com/jasmine/jasmine-ajax/blob/master/src/fakeRequest.js#L215), `getAllResponseHeaders()` returns the headers array joined by CRLF. When parsing the headers, superagent splits on CRLF and then [pops the last entry](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L203) with a comment "trailing CRLF".

The end result being that when you use jasmine-ajax with superagent, the last header gets stripped.

Looking at [the actual spec](http://www.w3.org/TR/XMLHttpRequest/#the-getallresponseheaders()-method), it doesn't say anything about requiring a trailing CRLF:
> Return all response headers, excluding headers that are a case-insensitive match for Set-Cookie or Set-Cookie2, as a single string, with each header line separated by a U+000D CR U+000A LF pair, excluding the status line, and with each header name and header value separated by a U+003A COLON U+0020 SPACE pair.

However, all major browsers I tested (Chrome, IE, Firefox) all include the trailing CRLF, so it might be worth staying consistent.

As a workaround, you can include an extra dummy header.

**Comment by slackersoft** [comment]
That's what I get for implementing to the spec... I'll take a look, this will probably go in as part of 3.0. which I'll try to get released soon, now that the github organization move has been updated in bower.
