### ISSUE TITLE
Cannot stub when using JSON data

### ISSUE THREAD

**Issue by PabloMD** [jasmine/jasmine-ajax#92]
Hi,
I have tried to mock/stub my ajax call, but it looks like it only works with text. When I tried to set response with object then my `done` callback is not called:

    jasmine.Ajax.stubRequest('/some_url/1').andReturn({
          //"responseText": response ,
         "response": response,
          "status": 200
        });

, but when I set responseText with object then it is called, but the responseJSON is not set, when debug response in FF

    responseJSON undefined
    status 200
    statusText "success"

Am I doing something wrong or it is an issue?

I am using Jasmine 2.1.3 and latest version of jasmine-ajax (honestly I cannot figure it out where I can find version I am using...;-), I've just downloaded mock-ajax.js from link in documentation in github)

**Comment by slackersoft** [comment]
`responseText` should be a string, so if you want it to be JSON, you should `JSON.stringify` it and put that in. As of 2.99 (and 3.0) you should be able to pass in just `response` and have that be set to the `response` property on the underlying XHR.

**Comment by slackersoft** [comment]
I've also made #93 to put some version information into the `mock-ajax.js` file that is downloaded.

**Comment by PabloMD** [comment]
Hi, sorry for late reply, in fact I have passed Object, After `JSON.stringify` everything works as expected. Thanks for reply
