### ISSUE TITLE
lib/mock-ajax.js should include some information about what version it is

### ISSUE THREAD

**Issue by slackersoft** [jasmine/jasmine-ajax#93]
It would be nice to be able to look at the `mock-ajax.js` file that has been downloaded and see what version number it roughly relates to.

Probably just pull it from `package.json` when concatenating the files together.

**Comment by dacresni** [comment]
also, why do we need to download it if it's included in the project's lib directory?

**Comment by slackersoft** [comment]
Some users don't use the NPM or bower packages, but just download the `mock-ajax.js` file directly from github. It is useful for them to be able to see at a glance which version of jasmine-ajax they are using to help us debug issues they may have.
