### ISSUE TITLE
When using stubRequest headers are not available when readyState is 2.

### ISSUE THREAD

**Issue by callmehiphop** [jasmine/jasmine-ajax#97]
I'm using `jasmine.Ajax.stubRequest` to stub out some headers, when I make my XHR request and the readyState is 2, my headers are not available. Per [line 268](https://github.com/jasmine/jasmine-ajax/blob/master/lib/mock-ajax.js#L268) it would appear that the stubbed data is not being applied until after onreadystatechange is fired.

**Comment by slackersoft** [comment]
What headers are you expecting to have available at a `readyState` of 2? Since the request hasn't been completed yet, anything you've set up in the request stub hasn't actually occurred, and the response hasn't actually been considered sent.

**Comment by callmehiphop** [comment]
All the headers, per the [spec](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Properties) `readyState` 2 occurs when the headers and status become available.

**Comment by slackersoft** [comment]
You're right. It looks like jasmine-ajax has been incorrectly setting the XHR to a `readyState` of 2 when sending the request.

We should either never transition to `readyState` 2 or only transition to it briefly in `respondWith` after setting the headers but before loading the rest of the response.

I'd be happy to review a pull request that did either of these.

**Comment by callmehiphop** [comment]
Ok, I'll have some time later this week to put a PR together if work hasn't started yet.
